# Generated by Django 5.1.5 on 2025-02-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
